### ISSUE TITLE
edition

### ISSUE THREAD

**Issue by 849025143** [genuinebyte/sunfright#3]
Will it support 1.12.2？

**Comment by genuinebyte** [comment]
It does not currently run on 1.12.2 but I'll work on getting it running under that version and make a release when it's working.

**Comment by genuinebyte** [comment]
I've got it working on 1.12.2 but it requires a different jar. The file is located under the GitHub releases tab and is begins `Sunfright_1.12.2`. [Here](https://github.com/genuinebyte/sunfright/releases/download/v1.0.0/Sunfright_1.12.2-1.0.0.jar) is a direct link to that file.
